source/css/scss/objects/_header.scss

Tall characters like Å are cropped. we set the line-height to 1.6 to get around this. Is there a better way to fix this?

fixed so names with Å are cropped: #11246

---

source/_patterns/03-maler-infoportal/20-navigasjonssider/60-arkiv.mustache
source/_patterns/04-sider-infoportal/20-navigasjonssider/60-arkiv-v-nyhetsarkiv.json
source/css/scss/objects/_newsArchive.scss
source/css/style.scss
source/js/production/infoportal/00-modules/newArchive.js
source/js/production/infoportal/00-modules/newsArchive.js
source/js/production/infoportal/init.js

Implemented the "load more" functionality for the news archive. For now we go the simple route, we load all the articles (should be rendered in the page by the server) and hide from the 6th on. Then the button shows them in batches of 5. It would be good to load them from the server in the future, but there's no API route at the moment, so I think this is OK to start with.

News Archive - implemented the load more functionality.

---

source/js/production/infoportal/00-modules/setupFormValidation.js

Fixes the following:
Validering av epost
1. Gå til kontaktskjemaet
2. Velg tema (radioknapp)
3. Fyll ut epost-feltet og trykk tab eller klikk i gjenta epost-feltet.
Feilmelding om at feltet er tomt kommer opp før man får anledning til å
skrive noe. Valideringen burde ikke skje før man forlater feltet
4. Fyll ut riktig epost adresse i gjenta epost-feltet
5. Endre opprinnelig epost adresse i feltet over, og klikk et annet
sted for å fjerne markøren fra epost-feltet. Nå kommer det ingen
feilmelding i gjenta epost-feltet. Her burde det også være en
validering når man endrer opprinnelig epost - alternativt at
valideringen kjøres på nytt når man klikker Send-knappen
Validering av navn
- Hvis man begynner å skrive noe i navnefeltet, og så fjerner
innholdet, kommer det feilmelding med én gang, …

Changes to validation logic.

---

gulpfile.js

The style-guide-export task now cleans the output directory first, and removes the html comments from the snippets.

Gulp export task for Jekyll

---

config/gulp/config.json
gulpfile.js
source/css/scss-altinnett/objects/_lists.scss
source/css/scss-brreg/objects/_buttons.scss
source/css/style-altinnett-base.scss
source/css/style-brreg-base.scss
source/css/style-brreg.scss
source/css/style.dist.brreg.scss
source/css/style.dist.storefront.scss

In storefront (https://altinn.github.io/designsystem-styleguide/) we need to switch themes, based on the selected project. So we came up with a new css-structure that allows us to do this easily.
- SCSS in altinnett was split into base and specific. Base ( style-altinnett-base.scss) contains everything needed from Bootstrap and Altinn. Specific (style-altinnett.scss) contains stuff only for Altinnett. All of the css in the specific files needs to be nested inside the class "project-altinnett". @msalte 
- A new file for storefront css was created, to contain all base stuff + all specific stuff from different projects.
- Added dummy test content for brreg, to test the switch in storefront.

New css structure for easy theme-switching in storefront

---

config/gulp/config.json
source/js/production/modules/ios11BugWorkaround.js

Workaround for a bug in iOS 11 that shows the cursor outside the input field the focus is on. Ref: https://bugs.webkit.org/show_bug.cgi?id=176896
You can see a GIF of it here: https://cdn-images-1.medium.com/max/1600/1*7ipWw7SAQ1VVJxnCUM933w.gif

Workaround for iOS 11 cursor bug

---

source/css/scss/objects/_buttons.scss

Chrome 62 adds a default border radius to <button> on macOS
Added border radius none to overwrite this.
https://www.chromestatus.com/features/5743649186906112

Added border radius 0 to buttons

---

source/_patterns/04-sider-portal/01-aktorvalg/10-aktorvalg.json
source/_patterns/04-sider-portal/01-aktorvalg/10-aktorvalg~forste-gang.json
source/_patterns/04-sider-portal/01-aktorvalg/15-aktorvalg-rediger-lagrede-sok.json
source/_patterns/04-sider-portal/50-innboks/20-innboks-soketreff-tvers.json
source/css/scss-common/base/_forms.scss
source/js/prototyping/modules/toggleSelectProfiles.js

- Substitute "small-checkboxes" with discreet variant (fixed in portal)
- Update button texts for actor selection
- Add "with subunits" option for actor selection
- Increase indentation of subunits displayed in actor selection
Denne PRen implementerer endringer som er blitt hotfikset inn i portal, samt en forbedring til utlisting av underaktører som er blitt bestilt av UX.
Siden det gjøres endringer i common CSS, legger jeg for ordens skyld inn flere reviewers, selv om klassene som her er brukt kun er benyttet i portal. "small-checkboxes" fjernes, da denne type checkbox finnes fra før i a-form-checkboxes--discret (portal er allerede oppdater med dette, så det er trygt å fjerne klassent).

Changes to actor selection in search across

---

source/css/scss-altinn/objects/_print.scss

Fix for IE and Firefox cutting of flexboesx when printing on multiple pages.
#13533 Lange utskrifter kuttes, kun første side kommer med

Changed card from flex to block for printing

---

source/_patterns/00-atomer/03-knapper/25-knapp-ikon-tekst.mustache
source/_patterns/01-molekyler/00-tekst/03-person-rolle.mustache
source/_patterns/01-molekyler/05-lister/_00-liste-innhold.mustache
source/_patterns/02-organismer/30-seksjoner/30-meny-personbytte.json
source/_patterns/02-organismer/30-seksjoner/31-personbytte.json
source/_patterns/04-sider-portal/01-aktorvalg/10-aktorvalg.json
source/_patterns/04-sider-portal/01-aktorvalg/10-aktorvalg~forste-gang.json
source/_patterns/04-sider-portal/50-innboks/00-innboks.json
source/_patterns/04-sider-portal/50-innboks/03-videresend-i-altinn.json
source/_patterns/04-sider-portal/92-andre-med-rettigheter/00-andre-med-rettigheter~roller-oversikt.json
source/css/scss-altinn/objects/_blocks.scss
source/css/scss-common/objects/_buttons.scss

The following pages are tested for the long name scenario
1) Videresend i Altinn - The role names can be long. This is fixed with css 'a-role-name' but the title doesn't seem to be displaying on hovering.
2) Innboks - Search names in the side panel is fixed. Tooltip is displayed on hover
3) Profil - Andre med rettigheter- Gi og fjerne rettigheter
long names fixed
4) Change Person - Lite aktørvalg
- Person name in list
-  Current person name

Added css, title attribute to show long names as ellipsis

---

source/js/production/modules/addListExpandHandler.js

Removing 'a-expanded' from siblings upon expanding a list item. This was previously not removed correctly, resulting in the "Utvid"/"Lukk" label not changing as expected.

Removing class from siblings upon expanding a list item

---

package.json
source/css/scss-altinn/objects/_blocks.scss

Moved the ellipsis styles from parent to the specific class for role name so that it works when the role name is within a child container also.

Moved the ellipsis styles to the a-personRole-name class

---

package-lock.json

New package-lock.json because bumped version.

New package-lock.json because bumped version.

---

package-lock.json
package.json
source/css/scss-common/base/_global-classes.scss

During commit to master #198 there was one missing "display" in CSS.
The text "added/lagt til" was not shown when adding roles.

Fixed missing css display in .a-visibleWhenCompleted

---

source/css/scss-common/base/_forms.scss

Fixed smaller "discreet" checkboxes getting correct sized "checkmarks" with a-form-checkboxes--discree class.

Fixed form check sizing for a-form-checkboxes--discreet.

---

config/gulp/config.json
source/_patterns/00-atomer/01-forms/10-tekst-input.mustache
source/_patterns/02-organismer/70-Modal-innhold/_93-delegering-roller.json
source/_patterns/02-organismer/70-Modal-innhold/_93-delegering-roller.mustache
source/_patterns/04-sider-portal/60-profil-roller-rettigheter/01-profil-roller-rettigheter.json
source/_patterns/04-sider-portal/92-andre-med-rettigheter/00-andre-med-rettigheter~egendefinert-rolle-rediger.json
source/_patterns/04-sider-portal/92-andre-med-rettigheter/00-andre-med-rettigheter~egendefinert-rolle.json
source/_patterns/04-sider-portal/92-andre-med-rettigheter/00-andre-med-rettigheter~roller-oversikt.json
source/css/scss-common/base/_global-classes.scss
source/js/prototyping/init.js
source/js/prototyping/modules/searchWithAutocomplete.js
source/js/prototyping/modules/searchWithAutocompleteVarselEnkeltTjeneste.js
source/js/prototyping/modules/searchWithMultipleSelectInAutoComplete.js

- Oppdatert resultat liste for tjenestesøk til å inneholde ServiceOwner under "Andre med rettigheter" og "Varsel for enkelttjenester"
- Oppdatert oppretting av en ny lokal rolle til samme nye design som "Lokal rolle rediger"

Tjenestesøk med ServiceOwner kolonne + Oppdatering av 'Ny lokal rolle' til det nye designet

---

source/css/scss-common/base/_global-classes.scss

This is to fix the alignment of the content in the strikeThrough-class so that it can be used in Internet Explorer

Modified strike through so that IE is satisfied

---

package-lock.json

After bump of npm-package the package-lock-file did not populate correctly. This merge should prevent later issues with the lock-file

correct package lock with npm 8.15.1

---

source/js/production/modules/popover.js

TFS bug 32392:
The roledelegation page for a new actor has two .modalPage elements (previous page also exists). 
This causes the selector to get the wrong (negative) height value. 
Fixed by making the selector only select the active modalPage, both for height retrieval and setting the padding value.

Fix for .modalPage height selector to select only the active/visible modal page

---

source/js/production/modules/colnav.min.js

This trigger was removed to fix bug IM-1999 affecting the schemaoverview on infoportal in november 2018, but the change was never added to the designguide.
The affected file is a module from the Zurb Foundation framework.

IM-1999 Removed click.zf.dropdownmenu event trigger

---

source/js/production/modules/altinnModal.js

These triggers were added to the dist files in infoportal when the eGuide functionality was added in 2018, but never added to the designguide.
The change makes sure events and handlers connected to `loaded.altinn.modal` are executed when a page is loaded as modal content.

Trigger loaded.altinn.modal when a modal loads new content

---

source/_patterns/00-atomer/01-forms/10-tekst-input.mustache
source/_patterns/04-sider-portal/92-andre-med-rettigheter/00-andre-med-rettigheter~roller-oversikt.json
source/css/scss-common/objects/_lists.scss
source/css/scss-common/objects/_messaging.scss

Det gjenstår en grafisk feil rundt bruken av a-autocomplete-container som brukes i:
- Professional.cshtml (valg av tjenester for varsling under "Din kontaktinformasjon for virksomheten")
- _ServiceSearch.cshtml (valg av tjenester for delegering under delegering av tjenesterettigheter og ved opprettelse av lokal rolle)
Fixen var slik at på den første desinfeilen reduserte min-width fra 200 til 100%
og for den andre feilen lagde vi en classe som hete "autocomplate-additional-classe" og satt den i 10-tekst-input.mustache. Der etter lagde vi ny css regel i _lists.scss som skal fikse liste-visningen i IPad screen.

Fixed design problemmet som  oppstår ved iPad-visning. 

---

source/css/scss-common/base/_forms.scss

The icon right inside search-input is moving left after interacting with input. Fixed with position relative.

Fix for Safari bug in search

---

package-lock.json
package.json
source/js/production/modules/altinnQuickhelp.js
source/js/production/modules/colnavCustom.js
source/js/production/modules/genericSearch.js
source/js/production/modules/listSort.js
source/js/production/modules/menuToggleEffect.js
source/js/production/modules/menuToggleEffectAltinnett.js
source/js/production/modules/personSwitcher.js
source/js/production/modules/togglePanel.js
source/js/production/modules/toggleRoleRights.js
source/js/prototyping/modules/nameChecker.js
source/js/prototyping/modules/onboardingUtilities.js

As a result when bumping from eslint version 3.18.1 to 4.18.2 some new lint-errors was introduced. All of them was of type "Expected indentation"-errors.

Bump eslint from 4.18.2 to 4.19.1 and corrected all lint-errors

---

source/css/scss-common/base/_forms.scss

Fix for focus-bug: When using keyboard (tab) to navigate in infoportal, portal and altinndigital, the checkboxes and radiobuttons had no visible focus-style.

Add dark-blue border to checkbox and radiobuttons when focus

---

source/css/scss-common/base/_forms.scss

This is to correct the current errors on the dropdown lists in altinn from:
to this:

minor margin-correction on dropdown list when dropdown is flipped up

---

source/css/scss-altinn/objects/_blocks.scss
source/css/scss-altinn/objects/_modal.scss

refactored to only show 2-column-view in screen size > than `d-lg`

minor adjustments for css in 2-column view

---

source/css/scss-common/base/_global-classes.scss

… av strek over operasjonsikon som ikke er "deselected" (Bug 47675)

Updated the CSS class .a-iconStrikeThrough with overflow-wrap:normal

---

source/css/scss-altinn/generic/_variables.scss
source/css/scss-common/objects/_buttons.scss
source/css/scss-common/objects/_modal.scss

..except modal backgrounds and buttons with black text.

mrosvik/changed primary blue color from #1EAEF7 to #008FD6..

---

source/css/scss-common/base/_global-classes.scss

Added class `a-disabledIcon` which only existed in combination with `a-iconStrikeThrough` before.

Adds class a-disabledIcon

---

package.json

PR 409 which bumps design system version from 3.0.0 to 3.0.1 added a dependency to node-sass by mistake.
node-sass again has dependency to node-gyp which has dependency to python, and causes all kinds of build errors when running npm install, unless the user has all the required build tools setup.

Update to remove node-sass depenceny
