source/js/production/modules/genericSearch.js

There was a bug in genericSearch when searching by expression (I only worked on the search by filters, but I broke the other search). This branch has a fix for it, maybe it should be included in v1.0.0?

Fix for search by expression in genericSearch.js

---

config/gulp/config.json
source/_patterns/03-maler-infoportal/01-forside/01-forside.mustache
source/_patterns/03-maler-infoportal/01-forside/_02-forside-innlogget.mustache
source/css/style.dist.infoportal-frontpage.scss
source/css/style.dist.infoportal.scss
source/css/style.scss
source/js/production/infoportal-frontpage-init.js

Added custom init-file for infoportal frontpage and custom css file for frontpage, too make a smaller version of css and js that can be loaded only for the frontpage in infoportal.

Custom js and css files for frontpage

---

source/css/scss/objects/_blocks.scss

Add break-word to .card-block

---

source/css/scss/objects/_buttons.scss
source/js/production/modules/searchFilterView.js

- Made search button fixed to the bottom of the screen
- Automatically move sticky help up when showing search button
#13655

New design for search filter button

---

README.md

Updated the readme to outline the simpler setup of the designsystem.

updated readme for new setup

---

source/_patterns/02-organismer/90-filter/01-filter.mustache
source/css/scss-common/objects/_buttons.scss
source/js/production/modules/searchFilterView.js

- Remove style for sticky search button for large screens
- Reposition sticky help only on small screens
- Remove hidden-toggle for search button
#14958

Fix behaviour of search button on large screens

---

source/data/getcategory.json
source/data/getprovider.json
source/js/production/modules/colnavCustom.js

- Menu structure is lazily created: only visible nodes are added
- Used native DOM for node creation instead of JQuery
- Removed unused code
- Optimized function invocation (some functions would be called in a loop where they only need to be called once).
- Added JSON data files from production for more realistic testing.
(this is a new branch with my changes for jhidalgo/colnav-slow-loading-issue, I deleted that branch because I committed some changes directly to master by mistake)

Performance optimizations for colnavCustom.js

---

source/_patterns/04-sider-altinnett/20-profil/10-profil~admin-asf.json

Added JSON for employee list to the profile page of the ASF user

janickef/Added JSON for employee list to the profile page of the ASF user

---

source/_patterns/02-organismer/30-seksjoner/80-login-dropdown.mustache
source/_patterns/04-sider-altinnett/10-forside/10-forside~admin-asf.json
source/_patterns/04-sider-altinnett/10-forside/10-forside~admin-leverandor.json
source/_patterns/04-sider-altinnett/10-forside/10-forside~personlig.json
source/_patterns/04-sider-altinnett/20-profil/10-profil~admin-asf.json
source/_patterns/04-sider-altinnett/20-profil/10-profil~admin-leverandor.json
source/_patterns/04-sider-altinnett/20-profil/10-profil~personlig.json
source/_patterns/04-sider-altinnett/30-artikkel/10-artikkel~admin-asf.json
source/_patterns/04-sider-altinnett/30-artikkel/10-artikkel~admin-leverandor.json
source/_patterns/04-sider-altinnett/30-artikkel/10-artikkel~personlig.json
source/_patterns/04-sider-altinnett/30-artikkel/20-artikkel-jumbo~admin-asf.json
source/_patterns/04-sider-altinnett/30-artikkel/20-artikkel-jumbo~admin-leverandor.json
source/_patterns/04-sider-altinnett/30-artikkel/20-artikkel-jumbo~personlig.json
source/_patterns/04-sider-altinnett/40-navigasjonssider/10-nyhetsarkiv~admin-asf.json
source/_patterns/04-sider-altinnett/40-navigasjonssider/10-nyhetsarkiv~admin-leverandor.json
source/_patterns/04-sider-altinnett/40-navigasjonssider/10-nyhetsarkiv~personlig.json
source/_patterns/04-sider-altinnett/50-seksjonsforsider/10-seksjonsforside~admin-asf.json
source/_patterns/04-sider-altinnett/50-seksjonsforsider/10-seksjonsforside~admin-leverandor.json
source/_patterns/04-sider-altinnett/50-seksjonsforsider/10-seksjonsforside~personlig.json
source/_patterns/04-sider-altinnett/60-sok/10-sok-forside~admin-asf.json
source/_patterns/04-sider-altinnett/60-sok/10-sok-forside~admin-leverandor.json
source/_patterns/04-sider-altinnett/60-sok/10-sok-forside~personlig.json
source/_patterns/04-sider-altinnett/60-sok/20-sok-skjema~admin-asf.json
source/_patterns/04-sider-altinnett/60-sok/20-sok-skjema~admin-leverandor.json
source/_patterns/04-sider-altinnett/60-sok/20-sok-skjema~personlig.json
source/_patterns/04-sider-altinnett/60-sok/30-sok-artikkel~admin-asf.json
source/_patterns/04-sider-altinnett/60-sok/30-sok-artikkel~admin-leverandor.json
source/_patterns/04-sider-altinnett/60-sok/30-sok-artikkel~personlig.json

Changing names of demo users to something more realistic.

Changing names of demo users to something more realistic

---

config/gulp/config.json
source/js/production/altinnett-init.js
source/js/prototyping/altinnett-prototyping-init.js

Added js to initialize and handle datepicker

Added js to initialize and handle datepicker

---

source/_patterns/02-organismer/30-seksjoner/80-login-dropdown.mustache
source/_patterns/04-sider-altinnett/10-forside/10-forside~admin-asf.json
source/_patterns/04-sider-altinnett/10-forside/10-forside~admin-leverandor.json
source/_patterns/04-sider-altinnett/10-forside/10-forside~personlig.json
source/_patterns/04-sider-altinnett/20-profil/10-profil~admin-asf.json
source/_patterns/04-sider-altinnett/20-profil/10-profil~admin-leverandor.json
source/_patterns/04-sider-altinnett/20-profil/10-profil~personlig.json
source/_patterns/04-sider-altinnett/30-artikkel/10-artikkel~admin-asf.json
source/_patterns/04-sider-altinnett/30-artikkel/10-artikkel~admin-leverandor.json
source/_patterns/04-sider-altinnett/30-artikkel/10-artikkel~personlig.json
source/_patterns/04-sider-altinnett/30-artikkel/20-artikkel-jumbo~admin-asf.json
source/_patterns/04-sider-altinnett/30-artikkel/20-artikkel-jumbo~admin-leverandor.json
source/_patterns/04-sider-altinnett/30-artikkel/20-artikkel-jumbo~personlig.json
source/_patterns/04-sider-altinnett/40-navigasjonssider/10-nyhetsarkiv~admin-asf.json
source/_patterns/04-sider-altinnett/40-navigasjonssider/10-nyhetsarkiv~admin-leverandor.json
source/_patterns/04-sider-altinnett/40-navigasjonssider/10-nyhetsarkiv~personlig.json
source/_patterns/04-sider-altinnett/50-seksjonsforsider/10-seksjonsforside~admin-asf.json
source/_patterns/04-sider-altinnett/50-seksjonsforsider/10-seksjonsforside~admin-leverandor.json
source/_patterns/04-sider-altinnett/50-seksjonsforsider/10-seksjonsforside~personlig.json
source/_patterns/04-sider-altinnett/60-sok/10-sok-forside~admin-asf.json
source/_patterns/04-sider-altinnett/60-sok/10-sok-forside~admin-leverandor.json
source/_patterns/04-sider-altinnett/60-sok/10-sok-forside~personlig.json
source/_patterns/04-sider-altinnett/60-sok/20-sok-skjema~admin-asf.json
source/_patterns/04-sider-altinnett/60-sok/20-sok-skjema~admin-leverandor.json
source/_patterns/04-sider-altinnett/60-sok/20-sok-skjema~personlig.json
source/_patterns/04-sider-altinnett/60-sok/30-sok-artikkel~admin-asf.json
source/_patterns/04-sider-altinnett/60-sok/30-sok-artikkel~admin-leverandor.json
source/_patterns/04-sider-altinnett/60-sok/30-sok-artikkel~personlig.json

Changed names of fictitious users according to specifications.

Changed names of fictitious users according to specifications

---

package.json
source/_patterns/02-organismer/30-seksjoner/30-meny-personbytte.json
source/css/scss-altinn/objects/_blocks.scss

Fix for alignment issue on a long name

Fix for aktorvalg person name issue

---

source/css/scss-common/objects/_card.scss

had to rewrite it for cards to work for infoportal.

there was an error with using :not with two classes, this does not work

---

source/_patterns/00-atomer/04-handlingsknapper/10-knapp-ikon.mustache
source/_patterns/04-sider-portal/91-klientdelegering/00-klientdelegering~gi-rettigheter-til-klienter.json
source/js/production/modules/popover.js

Fixed tab navigation for popover on checkbutton in client delegation

Fix for keyboard navigation in popover in client delegation

---

source/_patterns/02-organismer/70-Modal-innhold/12-videresend-til-dpi-info.json
source/_patterns/02-organismer/70-Modal-innhold/12-videresend-til-dpi-info.md
source/_patterns/02-organismer/70-Modal-innhold/12-videresend-til-dpi-info.mustache
source/_patterns/03-maler-portal/91-modal/01-modal.mustache
source/_patterns/04-sider-portal/50-innboks/16-videresend-til-dpi-info.json
source/_patterns/04-sider-portal/50-innboks/16-videresend-til-dpi-info.mustache

Added a new modal for showing information when the user has no digital postbox

Modal for showing information about digital postbox

---

source/_patterns/04-sider-portal/50-innboks/00-innboks.json
source/_patterns/04-sider-portal/50-innboks/01-innboks-kompakt.json

Added 2 inbox elements that shows notificaiton about the forwarded message to digital postbox

Inbox elements for dpi

---

source/_patterns/04-sider-portal/50-innboks/00-innboks.json
source/_patterns/04-sider-portal/50-innboks/16-videresend-til-dpi-info.json

1) Changed the "mer" text to "flere valg"
2) Moved the "Send til din eboks" option from overflow menu to the main menu of the inboxelement

Text changes for DPI

---

package-lock.json
package.json

bumped version to 2.3.0

---

package-lock.json

Reverted package-lock due to node-version change to 8.15.1

Reverted package-lock due to node-version change to 8.15.1

---

source/js/production/modules/personSwitcher.js

The problem was when in mobile view and switching between menu and personswitcher the menu appeared behind the personswitcher making the view a bit strange. The change in this PR is making sure that then one of them is open, the other one should be closed

Improved JavaScript for toggling menu and personswitcherlist on mobile

---

package-lock.json
package.json

bumped to new npm-version 2.3.2

---

source/css/scss-altinn/objects/_favourite.scss
source/js/production/modules/personSwitcher.js
source/js/prototyping/modules/searchWithAutocompleteVarselEnkeltTjeneste.js
source/js/prototyping/modules/searchWithMultipleSelectInAutoComplete.js

This pullrequest contains the following:
- fixed javascript so that mutationObserver is working in IE, 
- added ignore on font-size for favourite.css
- fixed error in linting js and scss

Fixed javascript so that mutationObserver is working in IE

---

package-lock.json
package.json

Prepare for new release of NPM package

bumped designsystem to new version 2.3.3

---

source/css/scss-common/objects/_article.scss

Dette gjelder både Altinn.no og Altinndigital.no

[ALTDIG-303] Alignet bulletpoints med tekst i artikler

---

.gitignore
source/_patterns/02-organismer/01-globale/90-header-altinnett.json
source/_patterns/02-organismer/01-globale/90-header-altinnett.mustache
source/css/scss-altinn/objects/_header.scss
source/css/scss-altinnett/base/_links-external.scss
source/css/scss-altinnett/objects/_header.scss
source/css/scss-common/base/_global-classes.scss
source/js/production/modules/menuToggleEffectAltinnett.js
source/js/prototyping/altinnett-prototyping-init.js

Ny header med ekspanderende søkefelt (Ref ALTDIG-310 i Jira)

Ny header for Altinn Digital

---

source/css/scss-altinnett/base/_forms.scss
source/css/scss-altinnett/objects/_article.scss

Pre-commit of scss got an ordering error in two files after latest merge. This PR fixes this issue

Fixing pre-commit of scss due to wrong ordering

---

package-lock.json
package.json

See release notes for more information

Bumped to new npm version to include delegationRequest styling

---

source/_patterns/00-atomer/07-tekst/_00-varsel-innhold.mustache
source/_patterns/02-organismer/_71-modal-gruppering/03-modal-kvittering.mustache
source/_patterns/04-sider-portal/10-modaler/70-tilgangsforesporsel~gi-tilgang-mangler-rettigheter.json
source/_patterns/04-sider-portal/92-andre-med-rettigheter/00-andre-med-rettigheter~tilgangsforesporsel-ikke-gjennomforbar.json
source/_patterns/04-sider-portal/92-andre-med-rettigheter/00-andre-med-rettigheter~tilgangsforesporsel.json

Added support for button with popover when trying to decline an AuthorizationRequest.

Added popover when trying to reject the authorization request

---

source/_patterns/02-organismer/01-globale/00-header.mustache
source/css/scss-altinn/objects/_header.scss
source/css/scss-altinnett/objects/_header.scss
source/css/scss-common/objects/_buttons.scss

Har lagt til utropstegn i meny knappen for mobil visning, og rettet opp hvordan den vises i selve menyen for mobilvisning

Endringer for utropstegn ved ubesvarte rettighetsforespørsler

---

source/_patterns/02-organismer/01-globale/00-header.mustache
source/css/scss-altinn/objects/_header.scss
source/css/scss-altinnett/objects/_header.scss
source/css/scss-common/objects/_buttons.scss

Reverts Altinn/DesignSystem#324

Revert "Endringer for utropstegn ved ubesvarte rettighetsforespørsler"

---

source/_patterns/02-organismer/01-globale/00-header.mustache
source/css/scss-altinn/objects/_header.scss
source/css/scss-altinnett/objects/_header.scss
source/css/scss-common/objects/_buttons.scss

Har fått godkjent designreview

Godkjent DesigReveiw

---

source/css/scss-altinn/objects/_header.scss
source/css/scss-altinnett/objects/_header.scss
source/css/scss-common/objects/_buttons.scss

Fixed 36 errors in scss-files that prevented the pre-commit to complete

Fixing lint-errors from pr 326

---

package-lock.json
package.json

bumped to new npm-version

---

package-lock.json
package.json

Reverts Altinn/DesignSystem#344

Revert "Bump jquery from 3.2.1 to 3.4.0"

---

source/_patterns/01-molekyler/05-lister/00-liste-unummerert.mustache
source/_patterns/02-organismer/50-ekspanderbart-panel/61-andre-med-rettigheter-liste-visning.json
source/_patterns/02-organismer/50-ekspanderbart-panel/61-andre-med-rettigheter-liste-visning.mustache
source/_patterns/03-maler-portal/60-profil-roller-rettigheter/50-profil-roller-rettigheter.mustache
source/css/scss-common/objects/_collapse.scss
source/css/scss-common/objects/_lists.scss

Reused the classes from client delegation, removed unecessary css for listview, added css for dark blue collapse button

Listview for others with rights

---

source/css/scss-common/objects/_collapse.scss

Needed two new classes to animate an arrow pointing down when a tab is collapsed and up when it is opened.

added classes for animating arrow that points down and up

---

source/css/scss-common/objects/_collapse.scss

Måtte stokke litt om på klassene for å få alt til å fungere riktig.

34638 request multiple rights simultaneously

---

source/_patterns/02-organismer/50-ekspanderbart-panel/61-andre-med-rettigheter-liste-visning.json
source/css/scss-common/base/_forms.scss

fixed reference that caused a warning and modified forms scroll overflow y to auto

fixed reference and modified forms scroll overflow y to auto

---

package-lock.json
package.json

Bump-commit to release a new version of altinn-designsystem NPM package

Bumped NPM version to 2.7.2

---

package-lock.json
package.json

Bumped to new version of altinn-designsystem

bumped to version 2.7.3

---

source/css/scss-common/objects/_collapse.scss
source/css/scss-common/objects/_lists.scss

The change is to support the new service search panel under others with rights in altinn.

Minor css-changes for others with rights panel

---

source/css/scss-altinn/objects/_modal.scss
source/css/scss-common/base/_global-classes.scss

Added logic for 2 column view in Altinn

added css for 2 column view

---

package-lock.json
package.json

Bumped to new npm package version 2.7.7

Bumped to new npm package version 2.7.7

---

source/css/scss-common/objects/_tabs.scss

added disabled-class for '.a-tab'-class

added disable-class for '.a-tab'-class

---

package-lock.json
package.json

bumped altinn-designsystem package number to 2.7.8

bumped npm version

---

package-lock.json
package.json

Bumped altinn-designsystem to 2.7.11

bumped to new version of npm

---

source/css/style.dist.tjenester3.scss

Replaced Roboto with Altinn-DIN for tjenester3

updated font for tjenester3 from roboto to altinn-din

---

source/css/scss-common/objects/_modal.scss
source/css/style.dist.tjenester3.scss

Updated the variable "letter-spacing" from "normal" to "0.3px" for tjenester3

updated letter-spacing from normal to 0.3 px

---

package-lock.json
package.json

bumped from version 3.0.0 to 3.0.1

bumped from version 3.0.0 to 3.0.1

---

package-lock.json
package.json

Bumped package.json design system version to 3.1.0 for new release

Bumped package.json design system version to 3.1.0 for new release

---

package-lock.json
package.json

Bump of DesignSystem version for new release 4.1.0

Bump of DesignSystem version for new release 4.1.0

---

README.md

This project is not maintained anymore, so we should add a warning about that.

Adding deprecation warning
